"""add_smart_working_schema

Revision ID: 1be86edca46d
Revises: 9f09bef2ac80
Create Date: 2026-01-08 13:03:43.435052+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1be86edca46d'
down_revision: Union[str, None] = '9f09bef2ac80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sw_agreements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('allowed_days_per_week', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'TERMINATED', 'DRAFT', name='sw_agreement_status', schema='smart_working'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('metadata_fields', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['auth.users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='smart_working'
    )
    op.create_index(op.f('ix_smart_working_sw_agreements_user_id'), 'sw_agreements', ['user_id'], unique=False, schema='smart_working')
    op.create_table('sw_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('agreement_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='sw_request_status', schema='smart_working'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('approval_request_id', sa.UUID(), nullable=True),
    sa.Column('approver_id', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agreement_id'], ['smart_working.sw_agreements.id'], ),
    # approval_request_id FK might point to approvals schema. Assuming approvals.approval_requests exists.
    sa.ForeignKeyConstraint(['approval_request_id'], ['approvals.approval_requests.id'], ),
    sa.ForeignKeyConstraint(['approver_id'], ['auth.users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='smart_working'
    )
    op.create_index(op.f('ix_smart_working_sw_requests_agreement_id'), 'sw_requests', ['agreement_id'], unique=False, schema='smart_working')
    op.create_index(op.f('ix_smart_working_sw_requests_date'), 'sw_requests', ['date'], unique=False, schema='smart_working')
    op.create_index(op.f('ix_smart_working_sw_requests_user_id'), 'sw_requests', ['user_id'], unique=False, schema='smart_working')
    op.create_table('sw_attendance',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('check_in', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True, comment='e.g. Home, Co-working'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['smart_working.sw_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id'),
    schema='smart_working'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sw_attendance', schema='smart_working')
    op.drop_index(op.f('ix_smart_working_sw_requests_user_id'), table_name='sw_requests', schema='smart_working')
    op.drop_index(op.f('ix_smart_working_sw_requests_date'), table_name='sw_requests', schema='smart_working')
    op.drop_index(op.f('ix_smart_working_sw_requests_agreement_id'), table_name='sw_requests', schema='smart_working')
    op.drop_table('sw_requests', schema='smart_working')
    op.drop_index(op.f('ix_smart_working_sw_agreements_user_id'), table_name='sw_agreements', schema='smart_working')
    op.drop_table('sw_agreements', schema='smart_working')
    # ### end Alembic commands ###
