"""add_enterprise_org_structure

Revision ID: 5c4ec4406a57
Revises: c7ddace1ecea
Create Date: 2026-01-05 07:28:05.634184+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c4ec4406a57'
down_revision: Union[str, None] = 'c7ddace1ecea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('hierarchy_level', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.UUID(), nullable=True),
    sa.Column('deputy_manager_id', sa.UUID(), nullable=True),
    sa.Column('cost_center_code', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deputy_manager_id'], ['auth.users.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['auth.users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['auth.departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='auth'
    )
    op.create_table('executive_levels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('hierarchy_level', sa.Integer(), nullable=False),
    sa.Column('escalates_to_id', sa.UUID(), nullable=True),
    sa.Column('max_approval_amount', sa.NUMERIC(precision=12, scale=2), nullable=True),
    sa.Column('can_override_workflow', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['escalates_to_id'], ['auth.executive_levels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='auth'
    )
    op.create_table('organizational_services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('coordinator_id', sa.UUID(), nullable=True),
    sa.Column('deputy_coordinator_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coordinator_id'], ['auth.users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['auth.departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deputy_coordinator_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='auth'
    )
    
    op.add_column('users', sa.Column('department_id', sa.UUID(), nullable=True), schema='auth')
    op.add_column('users', sa.Column('service_id', sa.UUID(), nullable=True), schema='auth')
    op.add_column('users', sa.Column('executive_level_id', sa.UUID(), nullable=True), schema='auth')
    
    op.create_foreign_key(None, 'users', 'executive_levels', ['executive_level_id'], ['id'], source_schema='auth', referent_schema='auth')
    op.create_foreign_key(None, 'users', 'organizational_services', ['service_id'], ['id'], source_schema='auth', referent_schema='auth')
    op.create_foreign_key(None, 'users', 'departments', ['department_id'], ['id'], source_schema='auth', referent_schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', schema='auth', type_='foreignkey')
    op.drop_constraint(None, 'users', schema='auth', type_='foreignkey')
    op.drop_constraint(None, 'users', schema='auth', type_='foreignkey')
    op.drop_column('users', 'executive_level_id', schema='auth')
    op.drop_column('users', 'service_id', schema='auth')
    op.drop_column('users', 'department_id', schema='auth')
    op.drop_table('organizational_services', schema='auth')
    op.drop_table('executive_levels', schema='auth')
    op.drop_table('departments', schema='auth')
    # ### end Alembic commands ###
