"""add_fifo_tracking_to_wallet

Revision ID: b49418a1226b
Revises: e4a097073c62
Create Date: 2026-01-02 06:29:21.547688+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b49418a1226b'
down_revision: Union[str, None] = 'e4a097073c62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet_transactions', sa.Column('remaining_amount', sa.Numeric(precision=6, scale=2), nullable=False, server_default='0'), schema='wallet')
    op.add_column('wallet_transactions', sa.Column('expiry_date', sa.Date(), nullable=True), schema='wallet')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallet_transactions', 'expiry_date', schema='wallet')
    op.drop_column('wallet_transactions', 'remaining_amount', schema='wallet')
    # ### end Alembic commands ###
