"""Add Monthly Timesheet and Settings

Revision ID: f68068de796c
Revises: 2b51fa85ac98
Create Date: 2026-01-09 17:06:57.910171+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f68068de796c'
down_revision: Union[str, None] = '2b51fa85ac98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hr_reporting_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timesheet_confirmation_day', sa.Integer(), nullable=False),
    sa.Column('timesheet_confirmation_month_offset', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='hr_reporting'
    )
    op.create_table('monthly_timesheets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('days', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('employee_notes', sa.Text(), nullable=True),
    sa.Column('hr_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='hr_reporting'
    )
    op.create_index(op.f('ix_hr_reporting_monthly_timesheets_employee_id'), 'monthly_timesheets', ['employee_id'], unique=False, schema='hr_reporting')
    op.create_index(op.f('ix_hr_reporting_monthly_timesheets_status'), 'monthly_timesheets', ['status'], unique=False, schema='hr_reporting')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hr_reporting_monthly_timesheets_status'), table_name='monthly_timesheets', schema='hr_reporting')
    op.drop_index(op.f('ix_hr_reporting_monthly_timesheets_employee_id'), table_name='monthly_timesheets', schema='hr_reporting')
    op.drop_table('monthly_timesheets', schema='hr_reporting')
    op.drop_table('hr_reporting_settings', schema='hr_reporting')
    # ### end Alembic commands ###
