"""create_wallet_schema

Revision ID: e4a097073c62
Revises: 018_add_recall_columns
Create Date: 2026-01-02 06:17:48.058806+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4a097073c62'
down_revision: Union[str, None] = '018_add_recall_columns'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('vacation_previous_year', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('vacation_current_year', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('vacation_accrued', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('vacation_used', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('vacation_used_ap', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('vacation_used_ac', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('rol_previous_year', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('rol_current_year', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('rol_accrued', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('rol_used', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('permits_total', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('permits_used', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('ap_expiry_date', sa.Date(), nullable=True),
    sa.Column('last_accrual_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='wallet'
    )
    op.create_index(op.f('ix_wallet_employee_wallets_user_id'), 'employee_wallets', ['user_id'], unique=False, schema='wallet')
    
    op.create_table('wallet_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('balance_type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallet.employee_wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='wallet'
    )
    
    # Missing tables from previous expenses update
    op.create_table('trip_attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['expenses.business_trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='expenses'
    )
    
    op.create_table('report_attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['expenses.expense_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='expenses'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_attachments', schema='expenses')
    op.drop_table('trip_attachments', schema='expenses')
    op.drop_table('wallet_transactions', schema='wallet')
    op.drop_index(op.f('ix_wallet_employee_wallets_user_id'), table_name='employee_wallets', schema='wallet')
    op.drop_table('employee_wallets', schema='wallet')
    # ### end Alembic commands ###
