"""add_count_saturday_as_leave

Revision ID: e1f019348a55
Revises: 20260107_2112
Create Date: 2026-01-07 20:58:18.950790+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1f019348a55'
down_revision: Union[str, None] = '20260107_2112'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted manually ###
    op.add_column('national_contract_versions', sa.Column('count_saturday_as_leave', sa.Boolean(), nullable=False, server_default='false'), schema='config')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - adjusted manually ###
    op.drop_column('national_contract_versions', 'count_saturday_as_leave', schema='config')
    # ### end Alembic commands ###
